### ISSUE TITLE
Random digits.

### ISSUE THREAD

**Issue by hydrogenium74** [WorldFamousElectronics/PulseSensor_Amped_Arduino#19]
![untitled](https://cloud.githubusercontent.com/assets/18221649/14221354/70abf5f2-f866-11e5-9c50-13dc0a0f83b5.png)
this is how it looks, just using the code on this forum and plugges my sensor in the arduino and uploaded the code om my Arduino anyone know why this happnes some help would be nice.

ps Thanks in advance

**Comment by hydrogenium74** [comment]
Fixed it the port my arduino was using wasnt right so just had to change it in the code.

**Comment by kratitripathi** [comment]
Where exactly did you make the change in the code? Facing the same issue.

**Comment by biomurph** [comment]
@kratitripathi it looks from the image that they have the baud rate set for 9600. It should be 115200.
You can change the baud rate settings in the lower right of the terminal window. There is a drop-down menu there.
