### ISSUE TITLE
No signal in ASCII Monitor

### ISSUE THREAD

**Issue by alecz1k** [WorldFamousElectronics/PulseSensor_Amped_Arduino#30]
Hello there, 

I ordered the pulse sensor from the official website. 
I run windows 10. I downloaded the code Pulse Sensor Amped Arduino from pulse sensor/GitHub.
I did the modification (static boolean serialVisual = true;) but when I run the Serial Monitor at 115200 baud I have nothing showing up. If I change baud, then I have random value showing up. 

In Processing, I have no signal even if the Arduino's port is recognized (I previously changed "static boolean serialVisual = true" back to false). 

What  am I doing wrong? 
Thank you for your help!

screenshots: 
flic.kr/p/NUyedW
flic.kr/p/NUyeeY

**Comment by biomurph** [comment]
Hi,
did you upload the code to you're board?

**Comment by alecz1k** [comment]
that was it,
thank you for your reply!
