### ISSUE TITLE
arduino 101-->"quick and dirt solution"

### ISSUE THREAD

**Issue by ciapatlano** [WorldFamousElectronics/PulseSensor_Amped_Arduino#36]
The code modifications mentioned in the "Timer _Interrupt_Notes" tab is diplaying error when verifying code. Specifically the line with "getPulse()" instead of "ISR(TIMER2_COMPA_vect)". See attached image
![getpulse_error](https://cloud.githubusercontent.com/assets/24862600/21581285/dbf6810e-d02b-11e6-9e97-3307ce8904b3.JPG)

**Comment by biomurph** [comment]
Oh, I see the problem. You need to add the word 'void' in front of getPulse() when you define the function. I have updated the notes in the repo, and verified that it does compile and function.

**Comment by ciapatlano** [comment]
thank you very much.
I will test it asap even if, in the mean time, I have found this:
[https://github.com/bneedhamia/PulseSensorBPM](url)
I let you check if it make sense to integrate that for 101.
