### ISSUE TITLE
Heart rate sensor is working incorrectly

### ISSUE THREAD

**Issue by osmnerl** [WorldFamousElectronics/PulseSensor_Amped_Arduino#37]
The sensor shows the BPM values ​​without putting my finger on it but I put my finger on the sensor and the values ​​are disappearing. Please help me this is my project homework and very little time left

**Comment by biomurph** [comment]
Hi,
You are not giving enough information to solve your problem.
Please upload the Arduino sketch with the variable 
`serialVisual = false;`
and then run the Processing sketch to see what the raw data looks like. You can take a screenshot and send it here. That will help.
When you put your finger on the Pulse Sensor, at first it may take a few seconds for the signal to settle.

**Comment by PrakharDutta** [comment]
this is the raw signal my pulse sensor gives even when my finger isn't touching the sensor.
![untitledpulse](https://user-images.githubusercontent.com/43348761/45635501-be10e480-bac2-11e8-887d-3706803cb6f8.jpg)

**Comment by biomurph** [comment]
It looks like the Pulse Sensor signal is idling very high. 
Please send a picture of the Pulse Sensor that you have. 
It looks like you are using an Arduino UNO, is that right?

**Comment by PrakharDutta** [comment]
yes, I'm using an arduino uno but i'm not entirely sure as to whether the sensor I have is legitimate
![img_20180917_234539](https://user-images.githubusercontent.com/43348761/45646416-e0195f80-bae0-11e8-8d1e-e704775ba646.jpg)

**Comment by PrakharDutta** [comment]
![img_20180917_234530](https://user-images.githubusercontent.com/43348761/45646919-3dfa7700-bae2-11e8-87e7-b9e07c4d0895.jpg)

**Comment by biomurph** [comment]
I can tell by the color of the wires and the rough edges of the PCB that you have purchased yourself a clone Pulse Sensor. I cannot troubleshoot hardware problems with hardware that I don't know anything about.
Please support the original makers of Pulse Sensor and buy from a reputable source.
www.pulsesensor.com
