### ISSUE TITLE
Error While Uploading

### ISSUE THREAD

**Issue by showmethemooney** [WorldFamousElectronics/PulseSensor_Amped_Arduino#39]
I followed the instructions and the code compiled without any errors but when uploading I got the following error.

Arduino: 1.8.1 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 3630 bytes (11%) of program storage space. Maximum is 32256 bytes.
Global variables use 237 bytes (11%) of dynamic memory, leaving 1811 bytes for local variables. Maximum is 2048 bytes.
avrdude: ser_open(): can't open device "/dev/cu.usbmodemfa131": No such file or directory
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by biomurph** [comment]
Did you notice that you selected the wrong serial port for the Uno board?
