### ISSUE TITLE
In function 'void interruptSetup()': error

### ISSUE THREAD

**Issue by kpssachin** [WorldFamousElectronics/PulseSensor_Amped_Arduino#49]
Arduino: 1.8.1  Board: "Arduino Due (Programming Port)"
In function 'void interruptSetup()':
 error: 'TCCR2A' was not declared in this scope
 TCCR2A = 0x02; 
error: 'TCCR2B' was not declared in this scope
TCCR2B = 0x06; 
error: 'OCR2A' was not declared in this scope
OCR2A = 0X7C;  
error: 'TIMSK2' was not declared in this scope
TIMSK2 = 0x02; 
error: 'sei' was not declared in this scope
sei();              

In function 'void TIMER2_COMPA_vect()':
error: 'cli' was not declared in this scope
cli();                                    
 error: 'sei' was not declared in this scope
 sei();                            

please help

**Comment by biomurph** [comment]
You are trying to compile code written for an UNO whilst targeting a DUE
Please read the Timer Interrupt Notes tab
