### ISSUE TITLE
Can I make work on Arduino 101?

### ISSUE THREAD

**Issue by frankthedead** [WorldFamousElectronics/PulseSensor_Amped_Arduino#53]
Time()?

**Comment by biomurph** [comment]
The Arduino 101 probably uses interrupts in it's own libraries, so you should probably not try to use the hardware timer interrupt. There is an example at the bottom of the Timer_Interrupt_Notes tab in the code 
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino/blob/master/PulseSensorAmped_Arduino_1.5.0/Timer_Interrupt_Notes.ino
That shows how to use a software timer that will work with pretty much any hardware microcontroller. Please use that and reply how it goes.

**Comment by frankthedead** [comment]
Thanks, get it working! Have a nice weekend.
