### ISSUE TITLE
How can I make work via bluetooth?

### ISSUE THREAD

**Issue by frankthedead** [WorldFamousElectronics/PulseSensor_Amped_Arduino#54]
Without using the data cable.
(Arduino 101 here)

**Comment by biomurph** [comment]
frankthedead,
Your question is too vague to answer in any way. Please be more specific.

**Comment by frankthedead** [comment]
How can I use the port /dev/tty.Bluetooth-Incoming-Port? For example, I want to monitor my pulse in my phone.

**Comment by biomurph** [comment]
It's not as easy as it sounds. First you need a bluetooth radio module that the Pulse Sensor can plug into. Look at Sparkfun or Adafruit for one of those.
Then you need code on the computer to monitor the incoming bluetooth signal. This is not a question that we are prepared to answer. You are asking for extensive design services that we don't provide

**Comment by yury-g** [comment]
The Arduino 101 makes this much easier then before.  We don't have an example project yet, but there are some great ones around the web.  See 👇
[https://create.arduino.cc/projecthub/masteruan/arduino-101-curie-ios-pulse-sensor-2441cd](https://create.arduino.cc/projecthub/masteruan/arduino-101-curie-ios-pulse-sensor-2441cd)
