### ISSUE TITLE
Getting BPM value in Serial MOnitor

### ISSUE THREAD

**Issue by ayush162883** [WorldFamousElectronics/PulseSensor_Amped_Arduino#69]
Is there any way to print the BPM values in Serial Monitor??

**Comment by bhavindave9** [comment]
Just download and install pulseSensor playground library in Arduino Ide and oper example section under file then select Getting_BPM_to_Monitor program to display bpm values in serial monitor

**Comment by biomurph** [comment]
Please use the Pulse Sensor Playground library. This code is deprecated.
https://github.com/WorldFamousElectronics/PulseSensorPlayground

In the doc below, you can find useful commands to access data in the library
getBeatsPerMinute() is a function you can call that returns the most recent BPM value.

https://github.com/WorldFamousElectronics/PulseSensorPlayground/blob/master/resources/PulseSensor%20Playground%20Tools.md
