### ISSUE TITLE
Help understanding Pulse sensor circuit 

### ISSUE THREAD

**Issue by rrn8055** [WorldFamousElectronics/PulseSensor_Amped_Arduino#75]
Can anyone please help me understand filtering and amplification part of pulse sensor amped circuit.
what C2,C3,C4, R3 and R4 are doing and which parts of the circuit contribute to RC low pass filter. I know its a interverting op-amp with gain of 330 with feedback resistors R6 and R5. I want to know what C2,C3,C4, and R3,R4 are doing.

![f57x6s2irrlffn8 1](https://user-images.githubusercontent.com/42450503/44231439-cbede580-a163-11e8-9e24-34ffe5974d56.png)

**Comment by biomurph** [comment]
This circuit was designed by trial and error, not with Spice or any other design tool.
R3 and R4 are dividing the voltage to make a reference on the + input of the opamp.
The capacitors are AC coupling the signal coming out of the APDS. That's about it.
