### ISSUE TITLE
 What is the accuracy of heart rate？

### ISSUE THREAD

**Issue by wangsong1982** [WorldFamousElectronics/PulseSensor_Amped_Arduino#78]
Please tell me，thx

**Comment by biomurph** [comment]
@wangsong1982 
Please note that this code has been superseded by the (PulseSensor Playground)[https://github.com/WorldFamousElectronics/PulseSensorPlayground] library.

The Pulse Sensor signal is sampled at 500Hz. This sample rate is adequate for determining BPM and IBI from the literature that we have researched.
