### ISSUE TITLE
arduino pulse sensor high output

### ISSUE THREAD

**Issue by rgranasinghe** [WorldFamousElectronics/PulseSensor_Amped_Arduino#80]
i download the PulseSensor Playground and try the "Getting_BPM_to_Monitor" example. when the program is upload and execute, even without placing the sensor on the finger it give the output as a heart beat is happened.  and when the sensor is placed on the finger the bpm value is getting increased up to 230 bpm. need to recover this problem. the code i used is,

/*  Getting_BPM_to_Monitor prints the BPM to the Serial Monitor, using the least lines of code and PulseSensor Library.
 *  Tutorial Webpage: https://pulsesensor.com/pages/getting-advanced
 *
--------Use This Sketch To------------------------------------------
1) Displays user's live and changing BPM, Beats Per Minute, in Arduino's native Serial Monitor.
2) Print: "♥  A HeartBeat Happened !" when a beat is detected, live.
2) Learn about using a PulseSensor Library "Object".
4) Blinks LED on PIN 13 with user's Heartbeat.
--------------------------------------------------------------------*/

#define USE_ARDUINO_INTERRUPTS true    // Set-up low-level interrupts for most acurate BPM math.
#include <PulseSensorPlayground.h>     // Includes the PulseSensorPlayground Library.   

//  Variables
const int PulseWire = 0;       // PulseSensor PURPLE WIRE connected to ANALOG PIN 0
const int LED13 = 13;          // The on-board Arduino LED, close to PIN 13.
int Threshold = 550;           // Determine which Signal to "count as a beat" and which to ignore.
                               // Use the "Gettting Started Project" to fine-tune Threshold Value beyond default setting.
                               // Otherwise leave the default "550" value.                                
                               
PulseSensorPlayground pulseSensor;  // Creates an instance of the PulseSensorPlayground object called "pulseSensor"

void setup() {   

  Serial.begin(9600);          // For Serial Monitor

  // Configure the PulseSensor object, by assigning our variables to it. 
  pulseSensor.analogInput(PulseWire);   
  pulseSensor.blinkOnPulse(LED13);       //auto-magically blink Arduino's LED with heartbeat.
  pulseSensor.setThreshold(Threshold);   

  // Double-check the "pulseSensor" object was created and "began" seeing a signal. 
   if (pulseSensor.begin()) {
    Serial.println("We created a pulseSensor Object !");  //This prints one time at Arduino power-up,  or on Arduino reset.  
  }
}

void loop() {

 int myBPM = pulseSensor.getBeatsPerMinute();  // Calls function on our pulseSensor object that returns BPM as an "int".
                                               // "myBPM" hold this BPM value now. 

if (pulseSensor.sawStartOfBeat()) {            // Constantly test to see if "a beat happened". 
 Serial.println("♥  A HeartBeat Happened ! "); // If test is "true", print a message "a heartbeat happened".
 Serial.print("BPM: ");                        // Print phrase "BPM: " 
 Serial.println(myBPM);                        // Print the value inside of myBPM. 
} 

  
  delay(20);                    // considered best practice in a simple sketch.

}

**Comment by abcd121298xyz** [comment]
is there a solution for this already? I have the same problem.
![image](https://user-images.githubusercontent.com/50367757/74012008-3338ce80-49c4-11ea-89f4-21462ba5eb2a.png)

**Comment by biomurph** [comment]
@abcd121298xyz are you saying that you get high BPM values and erroneous 'beats' without touching the Pulse Sensor? If so, that is just due to ambient light noise.
You can do something simple like just ignore any BPM values that are say over 180 or something with an if statement.

**Comment by abcd121298xyz** [comment]
How can I do so? The normal range of BPM IS 60-100, but I am receiving
around 230 bpm values.

**Comment by biomurph** [comment]
Are you getting those high values when you place the Pulse Sensor on your body?

**Comment by abcd121298xyz** [comment]
Yes. When I place it on the pulse points.. that is the value that i get..
though it is consistent

**Comment by biomurph** [comment]
What body parts are you placing the Pulse Sensor on? 
You should try the fingertip, and don't use a lot of pressure.

Also, please send me a picture of the Pulse Sensor you are using for verification.

**Comment by abcd121298xyz** [comment]
This one is when placed on the fingertips with not much pressure on the
sensor.

**Comment by biomurph** [comment]
Please send a picture of the Pulse Sensor

**Comment by abcd121298xyz** [comment]
![IMG_20200208_001532](https://user-images.githubusercontent.com/50367757/74046162-08bd3480-4a09-11ea-9369-4383aa8d3030.jpg)

![IMG_20200208_001559](https://user-images.githubusercontent.com/50367757/74046174-0d81e880-4a09-11ea-9c16-77868629c0a5.jpg)

**Comment by biomurph** [comment]
Thanks for sending that.
I can tell that what you have is not, in fact, a legit Pulse Sensor. 
That is likely the reason you are getting bad values.

Please support open source hardware and the original makers of Pulse Sensor by purchasing the real deal from trusted suppliers.
www.pulsesensor.com
www.adafruit.com
www.sparkfun.com
