### ISSUE TITLE
pulse sensor cut off frequencies

### ISSUE THREAD

**Issue by holly1551** [WorldFamousElectronics/PulseSensor_Amped_Arduino#85]
Hi,
can someone please tell me the cut off frequencies of this sensor. I need it to obtain a respiration rate from the PPG signal. For this, I need the the frequencies to be atleast 0.2Hz and above.

**Comment by biomurph** [comment]
@holly1551 The Pulse Sensor has some high pass filtration on it's output, so you will not see a classic PPG signal with DC offset and low frequency drift of the signal. 
If you want to derive respiration, you can use HRV.
https://github.com/WorldFamousElectronics/PulseSensor_Heart-Rate-Variabilty

**Comment by holly1551** [comment]
@biomurph thanks for replying!
Are you for certain that is doesn't contain frequencies from 0.2Hz and above? I cannot find how to derive respiration rate from HRV
